spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=BaiTap;encrypt=false}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO

spring.jpa.hibernate.ddl-auto=none

