spring.datasource.url=${DB_URL:jdbc:h2:mem:baitap;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:123456}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

app.jwt.secret=0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcd

